// DOM element references
const elements = {
    notesList: document.getElementById('notesList'),
    transcriptEditor: document.getElementById('transcriptEditor'),
    recordBtn: document.getElementById('recordBtn'),
    statusIndicator: document.getElementById('statusIndicator'),
    statusText: document.getElementById('statusText'),
    newNoteBtn: document.getElementById('newNoteBtn'),
    saveNoteBtn: document.getElementById('saveNoteBtn'),
    summarizeBtn: document.getElementById('summarizeBtn'),
    copySummaryBtn: document.getElementById('copySummaryBtn'),
    aiSummary: document.getElementById('aiSummary'),
    aiSummaryContent: document.getElementById('aiSummaryContent'),
    exportBtn: document.getElementById('exportBtn'),
    refreshNotesBtn: document.getElementById('refreshNotesBtn'),
    newNoteModal: document.getElementById('newNoteModal'),
    closeNewNoteModal: document.getElementById('closeNewNoteModal'),
    cancelNewNote: document.getElementById('cancelNewNote'),
    confirmNewNote: document.getElementById('confirmNewNote'),
    noteTitle: document.getElementById('noteTitle'),
    noteCourse: document.getElementById('noteCourse'),
    noteDate: document.getElementById('noteDate'),
    exportModal: document.getElementById('exportModal'),
    closeExportModal: document.getElementById('closeExportModal'),
    cancelExport: document.getElementById('cancelExport'),
    confirmExport: document.getElementById('confirmExport'),
    exportFileName: document.getElementById('exportFileName'),
    toast: document.getElementById('toast'),
    formatButtons: document.querySelectorAll('.format-btn'),
    exportFormatButtons: document.querySelectorAll('.export-format-btn'),
    mobileMenuToggle: document.getElementById('mobileMenuToggle'),
    sidebar: document.getElementById('sidebar'),
    notesSearch: document.getElementById('notesSearch'),
    currentNoteHeader: document.getElementById('currentNoteHeader'),
    currentNoteTitle: document.getElementById('currentNoteTitle'),
    currentNoteCourse: document.getElementById('currentNoteCourse'),
    currentNoteDate: document.getElementById('currentNoteDate'),
    imageUpload: document.getElementById('imageUpload')
};

export default elements;